### ISSUE TITLE
TypeError: Cannot read property 'hasCert' of undefined at lamassu-machine/lib/brain.js:148:21

### ISSUE THREAD

**Issue by sushrest** [lamassu/lamassu-machine#110]
On Ubuntu 16.04 when i run following command 

> node bin/lamassu-machine --mockTrader --mockCam --mockBillDispenser \
> --mockBTC 1KAkLnhU1BpvgjQUgLk1HF4PEgh4asFNS8 --mockBv /dev/pts/20

Outputs following error due to an undefined object on line 148 brain.js file in lib directory.

Output log:

2018-04-10T00:53:12.804Z LOG Lamassu Cryptomat software initialized.
2018-04-10T00:53:12.814Z LOG version: 2.0.6, cpuLoad: 0.44, memUse: 51.6 MB, memFree: 59.1%
  nodeUptime: 0.00h, osUptime: 42.59h
2018-04-10T00:53:12.814Z LOG lamassu-machine bailing out momentarily...
2018-04-10T00:53:12.815Z LOG TypeError: Cannot read property 'hasCert' of undefined
    at Brain.run (/home/sudhir/lamassu-machine/lib/brain.js:148:21)
    at startBrain (/home/sudhir/lamassu-machine/bin/lamassu-machine:34:9)
    at Object.<anonymous> (/home/sudhir/lamassu-machine/bin/lamassu-machine:40:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
2018-04-10T00:53:12.815Z LOG TypeError: Cannot read property 'hasCert' of undefined
    at Brain.run (/home/sudhir/lamassu-machine/lib/brain.js:148:21)
    at startBrain (/home/sudhir/lamassu-machine/bin/lamassu-machine:34:9)
    at Object.<anonymous> (/home/sudhir/lamassu-machine/bin/lamassu-machine:40:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
2018-04-10T00:53:12.816Z LOG server bound
2018-04-10T00:53:19.817Z LOG lamassu-machine bailing out
2018-04-10T00:53:19.817Z LOG lamassu-machine exiting

**Comment by naconner** [comment]
@sushrest v2.0.6 is an unreleased version from 2016.

Our production branch is v3. Instructions for running locally here:

https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu
