### ISSUE TITLE
Any Tutorial? 

### ISSUE THREAD

**Issue by Brooze2k01** [lamassu/lamassu-machine#113]
i followed all steps and im getting an error
im on linux mint

Error: Cannot find module 'clim'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kiosk/lamassu-machine/logging.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by naconner** [comment]
Hi. If running locally, we have a guide here: https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu

If you own one of our machines, please reach out to us at support@lamassu.is
