### ISSUE TITLE
Error when trying to pair to test server

### ISSUE THREAD

**Issue by H4dro** [lamassu/lamassu-machine#132]
Hi
Im getting the following error when trying to pair to the server

lamassu-machine v3.6.5
lamassu-server - Ubuntu 16.04 installed from the guide below)
https://support.lamassu.is/hc/en-us/articles/360007848211-Step-8-Installing-the-Lamassu-software

> node bin/lamassu-machine --mockBillValidator --mockBillDispenser --mockCam --mockPair "*TOTEM CODE FROM SERVER*"
> 
> 2018-08-11T12:32:02.595Z LOG crypto Machine software initialized.
> 2018-08-11T12:32:02.600Z LOG Listening on websocket localhost:8080
> 2018-08-11T12:32:02.603Z LOG USB reset not set up.
> 2018-08-11T12:32:02.606Z LOG new brain state: booting
> 2018-08-11T12:32:02.607Z LOG browser not connected
> 2018-08-11T12:32:02.607Z LOG DEBUG1
> 2018-08-11T12:32:02.608Z LOG new brain state: wifiConnected
> 2018-08-11T12:32:02.608Z LOG new brain state: unpaired
> 2018-08-11T12:32:02.608Z LOG server bound
> 2018-08-11T12:32:02.610Z LOG version: 3.6.5, cpuLoad: 1.25, memUse: 66.9 MB, memFree: 0.3%
>   nodeUptime: 0.00h, osUptime: 17.45h
> 2018-08-11T12:32:02.844Z LOG connected to browser
> 2018-08-11T12:32:03.395Z LOG connected to browser
> 2018-08-11T12:32:03.465Z LOG connected to browser
> 2018-08-11T12:32:13.125Z LOG new brain state: pairingScan
> 2018-08-11T12:32:18.129Z LOG new brain state: pairing
> 2018-08-11T12:32:18.187Z LOG RequestError: getaddrinfo ENOTFOUND :3000 :3000:3000
>     at StdError (/Users/hydro/lamassu-machine/node_modules/got/index.js:410:3)
>     at /Users/hydro/lamassu-machine/node_modules/got/index.js:430:3
>     at ClientRequest.req.once.err (/Users/hydro/lamassu-machine/node_modules/got/index.js:111:21)
>     at ClientRequest.g (events.js:292:16)
>     at emitOne (events.js:96:13)
>     at ClientRequest.emit (events.js:188:7)
>     at TLSSocket.socketErrorListener (_http_client.js:310:9)
>     at emitOne (events.js:96:13)
>     at TLSSocket.emit (events.js:188:7)
>     at connectErrorNT (net.js:1021:8)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> 2018-08-11T12:32:18.187Z LOG new brain state: pairingError

Thanks
Hydro

**Comment by H4dro** [comment]
Resolved by opening firewall port on vps correctly and using '' instead of "" for TOTEM id
