### ISSUE TITLE
Running locally requires further dependencies, throws errors

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-machine#22]
The latest version of lamassu-machine requires further dependencies than are indicated on `README.md` and thus running it locally is a more involved process.

Developers could benefit from a pre-built environment image for testing.

Experience on Xubuntu/Lubuntu 14.04 x64
------------
**From me:**

Could not get `node bin/lamassu-machine ...` to output logs. `start.html` returned teal screen in Chromium.

Ran:
```
// Where ^ represents already installed
 
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install -y node
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
^ sudo apt-get install -y npm
sudo apt-get install -y curl
sudo apt-get install -y ruby
^ sudo apt-get install -y make
^ sudo apt-get install -y python
^ sudo apt-get install -y gcc
sudo apt-get install -y libjpeg-dev
sudo apt-get install -y libpng-dev
sudo npm install -g node-gyp
sudo npm install -g node-pre-gyp
sudo npm install -g v4l2camera
sudo npm install -g serialport
// Downloaded/unpacked Linux-Universal (https://manateeworks.com/files/download_latest/mobiScan-Linux-Universal)
cd Linux-Universal/DemoApp
sudo cp libBarcodeScanner.* /usr/lib/
sudo cp libBarcodeScanner.* /usr/local/lib/
// Downloaded/unpacked node-manatee repo (https://github.com/lamassu/node-manatee)
cd node-manatee-master
node-gyp configure
node-gyp build
cd lamassu-machine-master
sudo npm install
./setup.sh
 
// In a separate terminal session, in lamassu-machine-master dir
ruby fake_id003.rb
 
// In main main terminal session
node bin/lamassu-machine --mock-btc 1KAkLnhU1BpvgjQUgLk1HF4PEgh4asFNS8 --mock-bv '<output from above>' --mock-trader
 
// Returns shell prompt rather than lamassu-machine logs
```

Experience on Ubuntu 12.04
-----------------------------
**From a developer:**

I'm using Ubuntu 12.04 LTS, by the way, with node v0.10.29.  I've had to follow a few steps which weren't in the instructions.

Initially, I had to get some libraries:
```
sudo apt-get install libjpeg-dev
sudo apt-get install libpng-dev
```
I went to the manatee website. Signed up, downloaded the SDK, moved `DemoApp/libBarcodeScanner.so` to `/usr/lib` (`/usr/lib/local` didn't work).

In order to launch the lamassu-machine binary, I also had to copy the `licenses.sample.json` to `licenses.json`.

I enter the command: `node bin/lamassu-machine --mock-btc 1MRGN3yU67v3oHjYYw9SDDKX1GX1ZgHiQu \
--mock-bv '/dev/ttys009' --mock-trader`

I use the bitcoin address which is controlled by bitcoind on my local machine.  This produces the following error message:
```
ypg@red ~/src/lamassu-machine $ node bin/lamassu-machine --mock-btc 1MRGN3yU67v3oHjYYw9SDDKX1GX1ZgHiQu --mock-bv '/dev/ttys009' --mock-trader
2014-09-14T20:52:39.896Z LOG brain-child bailing out momentarily...
2014-09-14T20:52:39.897Z LOG [Error: Registration failed]
2014-09-14T20:52:39.899Z LOG Error: Registration failed
    at Object.register (/home/ypg/src/lamassu-machine/node_modules/manatee/index.js:23:20)
    at Object.config (/home/ypg/src/lamassu-machine/lib/scanner.js:32:11)
    at new Brain (/home/ypg/src/lamassu-machine/lib/brain.js:47:16)
    at startBrain (/home/ypg/src/lamassu-machine/bin/brain-child:82:15)
    at Object.<anonymous> (/home/ypg/src/lamassu-machine/bin/brain-child:91:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Experience on Mac OS X
-------------------------
**Of an operator:**

Needs to download and configure Manatee libraries, although other node packages seem to be missing.

Errors upon `npm install` of `lamassu-machine`: https://gist.github.com/anonymous/dbb811372efc2fe745aa

**Comment by drkyro** [comment]
ive giving up getting it to run again on mac.

**Comment by naconner** [comment]
@drkyro Which version are you looking to run? 0.4.9 and up will require a Raqia API key, though this can be commented out: https://github.com/lamassu/lamassu-machine/issues/54 Glad to look at any logs.

**Comment by drkyro** [comment]
0.2.32-3

https://gist.github.com/drkyro/4e3c1f09abc8f5681708

**Comment by naconner** [comment]
@drkyro Might want to use the prebuilt node modules and libScanner in this update package:

https://drive.google.com/file/d/0B9KQ8CrumKjVaUw0YTlWQWdwUUk/view?usp=sharing

`/subpackage/hardware/aaeon/node_modules/`
`/subpackage/hardware/aaeon/lib/libBarcodeScanner.so`

`updatescript.js` refers to the paths these should be placed.

**Comment by dg175** [comment]
Hi,
I realize this is an old thread, just hoping somebody sees this and has a suggestion!
I'm fairly new so please forgive my inexperience with Ubuntu & github.

Is there a complete guide somewhere or list of instructions on how to get this up and running?  The instructions aren't complete (as pointed out by naconner).  

I believe I've added all the necessary dependencies, and have downloaded the manatee files and moved them to /lib.  When I get to the npm install, I'm getting a build error (below).  Any help or suggestions would be greatly appreciated!
Thanks,


dg@ubuntu:~/lamassu-machine$ npm install
npm http GET https://registry.npmjs.org/manatee
npm http 304 https://registry.npmjs.org/manatee

> manatee@0.2.1 install /home/dg/lamassu-machine/node_modules/manatee
> node-gyp rebuild

make: Entering directory `/home/dg/lamassu-machine/node_modules/manatee/build'
  CXX(target) Release/obj.target/manatee/src/manatee.o
  SOLINK_MODULE(target) Release/obj.target/manatee.node
/usr/bin/ld: skipping incompatible //usr/local/lib/libBarcodeScanner.so when searching for -lBarcodeScanner
/usr/bin/ld: skipping incompatible //usr/local/lib/libBarcodeScanner.a when searching for -lBarcodeScanner
/usr/bin/ld: cannot find -lBarcodeScanner
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/manatee.node] Error 1
make: Leaving directory `/home/dg/lamassu-machine/node_modules/manatee/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/dg/lamassu-machine/node_modules/manatee
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
dg@ubuntu:~/lamassu-machine$

**Comment by naconner** [comment]
Hi @dg175. There are a couple of dependencies that aren't needed when running the machine in harness, one of which is manatee.

Edit package.json to remove:

https://github.com/lamassu/lamassu-machine/blob/master/package.json#L17
https://github.com/lamassu/lamassu-machine/blob/master/package.json#L14

Then run `npm install`.

Also, before running lamassu-machine, comment out this block in brain.js:

https://github.com/lamassu/lamassu-machine/blob/master/lib/brain.js#L775-L809

Let me know how far that gets you.

**Comment by isysd** [comment]
As per @naconner's instructions above, it may also be required to remove the if clause around this line in brain.js:

https://github.com/lamassu/lamassu-machine/blob/master/lib/brain.js#L849

This basically refers to the section removed in:

https://github.com/lamassu/lamassu-machine/blob/master/lib/brain.js#L775-L809

**Comment by dg175** [comment]
Thanks guys. I've commented out the manatee and jpeg dependencies as well as the code block in brain.js.
Still have some install issues as it looks like jpeg is referenced in another package.json file under /node_modules.  Not sure how to remove the reference to this?

I'd actually like to get it running with the ability to use the webcam at some point rather than just commenting it all out.  I assume that the jpeg and manatee dependencies would be necessary at that point.  Any idea what is screwing up the install when these are left in place?


Here's the output from my last install attempt:

dg@ubuntu:~/lamassu-machine$ npm install

> jpeg@2.0.0 install /home/dg/lamassu-machine/node_modules/jpeg
> node-gyp configure build

make: Entering directory `/home/dg/lamassu-machine/node_modules/jpeg/build'
  CXX(target) Release/obj.target/jpeg/src/common.o
  CXX(target) Release/obj.target/jpeg/src/jpeg_encoder.o
In file included from ../src/jpeg_encoder.cpp:1:0:
../src/jpeg_encoder.h: In constructor ‘JpegEncoder::JpegEncoder(unsigned char*, int, int, int, buffer_type)’:
../src/jpeg_encoder.h:12:20: warning: ‘JpegEncoder::data’ will be initialized after [-Wreorder]
     unsigned char *data;
                    ^
../src/jpeg_encoder.h:10:9: warning:   ‘int JpegEncoder::width’ [-Wreorder]
     int width, height, quality, smoothing;
         ^
../src/jpeg_encoder.cpp:3:1: warning:   when initialized here [-Wreorder]
 JpegEncoder::JpegEncoder(unsigned char *ddata, int wwidth, int hheight,
 ^
  CXX(target) Release/obj.target/jpeg/src/jpeg.o
  CXX(target) Release/obj.target/jpeg/src/fixed_jpeg_stack.o
  CXX(target) Release/obj.target/jpeg/src/dynamic_jpeg_stack.o
In file included from ../src/dynamic_jpeg_stack.cpp:8:0:
../src/dynamic_jpeg_stack.h: In constructor ‘DynamicJpegStack::DynamicJpegStack(buffer_type)’:
../src/dynamic_jpeg_stack.h:20:10: warning: ‘DynamicJpegStack::dyn_rect’ will be initialized after [-Wreorder]
     Rect dyn_rect; // rect of dynamic push area (updated after each push)
          ^
../src/dynamic_jpeg_stack.h:19:9: warning:   ‘int DynamicJpegStack::bg_width’ [-Wreorder]
     int bg_width, bg_height; // background width and height after setBackground
         ^
../src/dynamic_jpeg_stack.cpp:32:1: warning:   when initialized here [-Wreorder]
 DynamicJpegStack::DynamicJpegStack(buffer_type bbuf_type) :
 ^
In file included from ../src/dynamic_jpeg_stack.cpp:8:0:
../src/dynamic_jpeg_stack.h:19:19: warning: ‘DynamicJpegStack::bg_height’ will be initialized after [-Wreorder]
     int bg_width, bg_height; // background width and height after setBackground
                   ^
../src/dynamic_jpeg_stack.h:17:20: warning:   ‘unsigned char* DynamicJpegStack::data’ [-Wreorder]
     unsigned char *data;
                    ^
../src/dynamic_jpeg_stack.cpp:32:1: warning:   when initialized here [-Wreorder]
 DynamicJpegStack::DynamicJpegStack(buffer_type bbuf_type) :
 ^
  CXX(target) Release/obj.target/jpeg/src/module.o
  SOLINK_MODULE(target) Release/obj.target/jpeg.node
  SOLINK_MODULE(target) Release/obj.target/jpeg.node: Finished
  COPY Release/jpeg.node
make: Leaving directory `/home/dg/lamassu-machine/node_modules/jpeg/build'
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport requires async@'0.9.0' but will load
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/async,
npm WARN unmet dependency which is version 0.2.10
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport/node_modules/node-pre-gyp requires tar@'~2.1.0' but will load
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/tar,
npm WARN unmet dependency which is version 0.1.20
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator requires bluebird@'^2.9.25' but will load
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/bluebird,
npm WARN unmet dependency which is version 2.4.3
dg@ubuntu:~/lamassu-machine$ 

Thanks again,

**Comment by dg175** [comment]
Ran the NMP install again, and it completes now (with some warnings).  ./setup seems to run fine.  I've got the mock validator running in another terminal, and tried starting up the lamassu-machine, but unfortunately it bails out..


dg@ubuntu:~/lamassu-machine$ sudo npm install
[sudo] password for dg: 

> jpeg@2.0.0 install /home/dg/lamassu-machine/node_modules/jpeg
> node-gyp configure build

make: Entering directory `/home/dg/lamassu-machine/node_modules/jpeg/build'
make: Nothing to be done for `all'.
make: Leaving directory `/home/dg/lamassu-machine/node_modules/jpeg/build'
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport requires async@'0.9.0' but will load
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/async,
npm WARN unmet dependency which is version 0.2.10
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport/node_modules/node-pre-gyp requires tar@'~2.1.0' but will load
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/tar,
npm WARN unmet dependency which is version 0.1.20
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/serialport/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator requires bluebird@'^2.9.25' but will load
npm WARN unmet dependency /home/dg/lamassu-machine/node_modules/bluebird,
npm WARN unmet dependency which is version 2.4.3
dg@ubuntu:~/lamassu-machine$ ./setup.sh

node_modules folder found. skipping dependency install.
Downloading fonts...
######################################################################## 100.0%
######################################################################## 100.0%
Installing fonts in lamassu-machine...
Setting up config files...
Setting up keys...
Successful installation.
dg@ubuntu:~/lamassu-machine$

dg@ubuntu:~/lamassu-machine$ node bin/lamassu-machine --mockBTC 1MzwEor6jktsQ3TRg2jmW5hjMH14wSYdZA --mockBv /dev/pts/12 --mockTrader --mockCam
2016-03-25T17:07:21.566Z LOG lamassu-machine bailing out momentarily...
2016-03-25T17:07:21.569Z LOG { [Error: Cannot find module 'debug'] code: 'MODULE_NOT_FOUND' }
2016-03-25T17:07:21.571Z LOG Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/dg/lamassu-machine/node_modules/serialport/serialport.js:9:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/dg/lamassu-machine/lib/id003/id003rs232.js:3:18)
2016-03-25T17:07:28.575Z LOG lamassu-machine bailing out
2016-03-25T17:07:28.575Z LOG lamassu-machine exiting
dg@ubuntu:~/lamassu-machine$

**Comment by naconner** [comment]
@dg175 Thanks for the output. Does this produce the same when starting off with a newly cloned directory (removing `jpeg` and `manatee` before running npm install)?

Also, what's the result of `node -v` on your system?

I may be able to create a docker with the machine software pre-configured.

**Comment by dg175** [comment]
Node version is v0.10.25.

I cloned to a new directory, and it seems to build without error.  Tried running the mock validator, and then the lamassu machine software, but it bails out with the below output:


dg@ubuntu:~/samplelamassu/lamassu-machine$ node bin/lamassu-machine --mockBTC 1BF2cZmCuaxRyk64PF9iXAy3iv9Q2bu4gJ \
> --mockBv /dev/pts/12 --mockTrader --mockCam
2016-03-28T18:42:23.723Z LOG Bitcoin Machine software initialized.
2016-03-28T18:42:23.783Z LOG new brain state: booting
2016-03-28T18:42:23.783Z LOG browser not connected
2016-03-28T18:42:23.783Z LOG DEBUG1
2016-03-28T18:42:23.790Z LOG { lo: 
   [ { address: '127.0.0.1',
       family: 'IPv4',
       internal: true },
     { address: '::1',
       family: 'IPv6',
       internal: true } ],
  eth0: 
   [ { address: '192.168.146.128',
       family: 'IPv4',
       internal: false },
     { address: 'fe80::20c:29ff:feb9:6369',
       family: 'IPv6',
       internal: false } ] }
2016-03-28T18:42:23.791Z LOG [ 'eth0' ]
2016-03-28T18:42:23.791Z LOG new brain state: wifiConnected
2016-03-28T18:42:23.792Z LOG FSM: start [ none -> Start ]
2016-03-28T18:42:23.799Z LOG version: 0.5.18, cpuLoad: 0.19, memUse: 28.2 MB, memFree: 7.6%
  nodeUptime: 0.00h, osUptime: 11.89h
2016-03-28T18:42:23.802Z LOG server bound
2016-03-28T18:42:23.806Z LOG FSM: connect [ Start -> Connected ]
2016-03-28T18:42:23.910Z LOG FSM: disable [ Connected -> Disable ]
2016-03-28T18:42:23.910Z LOG FSM: denominations [ Disable -> Denominations ]
2016-03-28T18:42:24.009Z LOG FSM: initialize [ Denominations -> Initialize ]
2016-03-28T18:42:24.312Z LOG Bill validator connected.
2016-03-28T18:42:24.312Z LOG Using mock trader
2016-03-28T18:42:24.314Z LOG New sessionId: dd020768-b6c5-4796-b692-baeee510f644
2016-03-28T18:42:24.314Z LOG lightOff
2016-03-28T18:42:24.316Z LOG new brain state: pendingIdle
2016-03-28T18:42:24.317Z LOG lamassu-machine bailing out momentarily...
2016-03-28T18:42:24.318Z LOG [TypeError: Object [object Object] has no method '_ensureRaqiaRegistration']
2016-03-28T18:42:24.320Z LOG TypeError: Object [object Object] has no method '_ensureRaqiaRegistration'
    at _idle (/home/dg/samplelamassu/lamassu-machine/lib/brain.js:851:10)
    at _restart (/home/dg/samplelamassu/lamassu-machine/lib/brain.js:1171:8)
    at _networkUp (/home/dg/samplelamassu/lamassu-machine/lib/brain.js:1130:10)
    at null.<anonymous> (/home/dg/samplelamassu/lamassu-machine/lib/brain.js:323:50)
    at EventEmitter.emit (events.js:92:17)
    at run (/home/dg/samplelamassu/lamassu-machine/lib/mocks/trader.js:48:8)
    at /home/dg/samplelamassu/lamassu-machine/lib/brain.js:238:17
    at null.<anonymous> (/home/dg/samplelamassu/lamassu-machine/lib/id003/id003.js:166:16)
    at wrapper (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
2016-03-28T18:42:27.049Z LOG FSM: disable [ Initialize -> Disable ]
2016-03-28T18:42:31.322Z LOG lamassu-machine bailing out
2016-03-28T18:42:31.323Z LOG lamassu-machine exiting
dg@ubuntu:~/samplelamassu/lamassu-machine$ 

Thanks,

**Comment by naconner** [comment]
Latest instructions here, including resolution to Raqia registration error: https://github.com/lamassu/lamassu-machine/wiki/Running-on-Ubuntu-14.04-i386

**Comment by AradeaTechno** [comment]
Hi, i'm trying to use lamassu-macine in ubuntu 14.04.

when run the mock, i'm facing this error.

```
xxx@xxx:~/GitHub/lamassu-machine$ node bin/lamassu-machine --mockBTC 1KAkLnhU1BpvgjQUgLk1HF4PEgh4asFNS8 --mockBv /dev/pts/28 --mockTrader --mockCam
2017-10-05T08:21:09.769Z LOG lamassu-machine bailing out momentarily...
2017-10-05T08:21:09.773Z LOG { Error: Cannot find module '/home/xxx/GitHub/lamassu-machine/node_modules/serialport/build/serialport/v1.7.4/Release/node-v48-linux-x64/serialport.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxx/GitHub/lamassu-machine/node_modules/serialport/serialport.js:14:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
2017-10-05T08:21:09.774Z LOG Error: Cannot find module '/home/xxx/GitHub/lamassu-machine/node_modules/serialport/build/serialport/v1.7.4/Release/node-v48-linux-x64/serialport.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxx/GitHub/lamassu-machine/node_modules/serialport/serialport.js:14:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
2017-10-05T08:21:16.779Z LOG lamassu-machine bailing out
2017-10-05T08:21:16.780Z LOG lamassu-machine exiting

```

Please help, to fix this.

Thx in advance
