### ISSUE TITLE
lamassu-machine bailing out

### ISSUE THREAD

**Issue by jamesdwilson** [lamassu/lamassu-machine#53]
$ node bin/lamassu-machine --mockBTC 1KAkLnhU1BpvgjQUgLk1HF4PEgh4asFNS8 --mockBv /dev/pts/8 --mockTrader --mockCam
2015-03-04T06:18:45.081Z LOG Bitcoin Machine software initialized.
2015-03-04T06:18:45.088Z LOG new brain state: booting
2015-03-04T06:18:45.088Z LOG browser not connected
2015-03-04T06:18:45.089Z LOG new brain state: wifiConnected
2015-03-04T06:18:45.090Z LOG FSM: start [ none -> Start ]
2015-03-04T06:18:45.092Z LOG cpuLoad: 0.51, memUse: 28.7 MB, memFree: 5.3%
  nodeUptime: 0.00h, osUptime: 105.10h
2015-03-04T06:18:45.093Z LOG server bound
2015-03-04T06:18:45.094Z LOG FSM: connect [ Start -> Connected ]
2015-03-04T06:18:45.200Z LOG FSM: disable [ Connected -> Disable ]
2015-03-04T06:18:45.202Z LOG FSM: denominations [ Disable -> Denominations ]
2015-03-04T06:18:45.300Z LOG FSM: initialize [ Denominations -> Initialize ]
2015-03-04T06:18:45.594Z LOG Bill validator connected.
2015-03-04T06:18:45.595Z LOG Using mock trader
2015-03-04T06:18:45.596Z LOG New sessionId: 5c48225d-f217-4cd3-8823-51cb24ea64a2
2015-03-04T06:18:45.596Z LOG lightOff
2015-03-04T06:18:45.596Z LOG new brain state: pendingIdle
2015-03-04T06:18:45.597Z LOG New sessionId: df24c302-71ef-4189-807e-6e85036325cf
2015-03-04T06:18:45.597Z LOG lightOff
2015-03-04T06:18:45.597Z LOG lamassu-machine bailing out momentarily...
2015-03-04T06:18:45.599Z LOG [TypeError: Object [object Object] has no method 'raqia']
2015-03-04T06:18:45.599Z LOG TypeError: Object [object Object] has no method 'raqia'
    at /home/james/projects/lamassu-machine/lib/brain.js:712:17
    at fs.js:208:20
    at Object.oncomplete (fs.js:108:15)
2015-03-04T06:18:45.621Z LOG connected to browser
2015-03-04T06:18:46.306Z LOG FSM: disable [ Initialize -> Disable ]
2015-03-04T06:18:51.605Z LOG connected to browser
2015-03-04T06:18:52.600Z LOG lamassu-machine bailing out
2015-03-04T06:18:52.601Z LOG lamassu-machine exiting
james@agape ~/projects/lamassu-machine $

**Comment by jamesdwilson** [comment]
It just exits by itself after a few seconds

**Comment by naconner** [comment]
Hi @jamesdwilson The version you're working with requires API access to our Raqia server when running in two-way mode (used for zero-conf and SMS redemption).

As per https://github.com/lamassu/lamassu-machine/issues/54, this can be bypassed.
