### ISSUE TITLE
Error: Cannot find module '../device_config.json'

### ISSUE THREAD

**Issue by songproducer** [lamassu/lamassu-machine#75]
Ubuntu 14.04

sudo nodejs bin/lamassu-machine --mockBtc 1KAkLnhU1BpvgjQUgLk1HF4PEgh4asFNS8 --mockBv /dev/pts/12 --mockCam

module.js:340
    throw err;
          ^
Error: Cannot find module '../device_config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/leotreasure/lamassu-machine/lib/configuration.js:8:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by songproducer** [comment]
Just realised I missed these steps:

./setup.sh
mv licenses.sample.json licenses.json
