### ISSUE TITLE
Can't find module Serialport

### ISSUE THREAD

**Issue by AradeaTechno** [lamassu/lamassu-machine#89]
Hi, i'm trying to install lamassu-machine in ubuntu 14.04.
On run mock i got this error.

```
xxx@xxx:~/GitHub/lamassu-machine$ node bin/lamassu-machine --mockBTC 1KAkLnhU1BpvgjQUgLk1HF4PEgh4asFNS8 --mockBv /dev/pts/28 --mockTrader --mockCam
2017-10-05T08:21:09.769Z LOG lamassu-machine bailing out momentarily...
2017-10-05T08:21:09.773Z LOG { Error: Cannot find module '/home/xxx/GitHub/lamassu-machine/node_modules/serialport/build/serialport/v1.7.4/Release/node-v48-linux-x64/serialport.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxx/GitHub/lamassu-machine/node_modules/serialport/serialport.js:14:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
2017-10-05T08:21:09.774Z LOG Error: Cannot find module '/home/xxx/GitHub/lamassu-machine/node_modules/serialport/build/serialport/v1.7.4/Release/node-v48-linux-x64/serialport.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxx/GitHub/lamassu-machine/node_modules/serialport/serialport.js:14:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
2017-10-05T08:21:16.779Z LOG lamassu-machine bailing out
2017-10-05T08:21:16.780Z LOG lamassu-machine exiting

```

How to fix it ? Please help.

thx in advance

**Comment by naconner** [comment]
Hi Aradea, have the instructions here been followed?

https://github.com/lamassu/lamassu-machine/wiki/Running-v2-on-Ubuntu-14.04-i386

In any case, we've since moved to developing on our beta:

https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu

**Comment by AradeaTechno** [comment]
Hi naconner,
I'll give a try for both of them now. Thx for the support

**Comment by AradeaTechno** [comment]
Hi @naconner  , 

This is what happened when i try to install v2

```
xxx@xxx:~/lamassu-machine$ sudo nodejs bin/lamassu-machine --mockBtc 1KAkLnhU1BpvgjQUgLk1HF4PEgh4asFNS8 --mockBv /dev/pts/25 --mockCam
2017-10-06T06:14:04.149Z LOG lamassu-machine bailing out momentarily...
2017-10-06T06:14:04.153Z LOG { Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxx/lamassu-machine/lib/id003/id003rs232.js:3:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
2017-10-06T06:14:04.154Z LOG Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxx/lamassu-machine/lib/id003/id003rs232.js:3:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
2017-10-06T06:14:11.162Z LOG lamassu-machine bailing out
2017-10-06T06:14:11.162Z LOG lamassu-machine exiting
xxx@xxx:~/lamassu-machine$ 
```

**Comment by AradeaTechno** [comment]
On V3, where i can find "Add New Machine" button ? 
Which admin page ? is it admin page that installed with lamassu-install repo ??
I've install lamassu-server, lamassu-admin, but i can't find "Add New Machine" button inside it.

**Comment by AradeaTechno** [comment]
@naconner , don't know why today it works well. nothing change but it works...
I think the problem solved right now..

**Comment by naconner** [comment]
@AradeaTechno Glad it works. For anything else, we provide support for machine operators via email at support@lamassu.is.
