### ISSUE TITLE
lamassu-machine exiting / bailing out 

### ISSUE THREAD

**Issue by darshil** [lamassu/lamassu-machine#98]
I am getting lamassu-machine bailing out.

LOG [TypeError: Object [object Object] has no method 'raqia'] 

I read #53 and #54 but wasn't able to find a clear cut solution. 

`2018-01-30T01:33:43.079Z LOG new brain state: wifiConnected
2018-01-30T01:33:43.080Z LOG FSM: start [ none -> Start ]
2018-01-30T01:33:43.082Z LOG version: 0.1.0, cpuLoad: 1.84, memUse: 37.2 MB, memFree: 3.1%
  nodeUptime: 0.00h, osUptime: 148.27h
2018-01-30T01:33:43.082Z LOG server bound
2018-01-30T01:33:43.083Z LOG FSM: connect [ Start -> Connected ]
2018-01-30T01:33:43.190Z LOG DEBUG100: denominations
2018-01-30T01:33:43.190Z LOG FSM: disable [ Connected -> Disable ]
2018-01-30T01:33:43.191Z LOG DEBUG101: denominations, 0x8a, 61010100620000006301050064010a0065011400660132006701640068000000
2018-01-30T01:33:43.191Z LOG FSM: denominations [ Disable -> Denominations ]
2018-01-30T01:33:43.191Z LOG DEBUG100: reset
2018-01-30T01:33:43.191Z LOG DEBUG101: ack, 0x50, null
2018-01-30T01:33:43.288Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:43.288Z LOG FSM: initialize [ Denominations -> Initialize ]
2018-01-30T01:33:43.288Z LOG DEBUG100: interruptMode
2018-01-30T01:33:43.392Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:43.497Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:43.585Z LOG Bill validator connected.
2018-01-30T01:33:43.585Z LOG Using mock trader
2018-01-30T01:33:43.587Z LOG New sessionId: c565e14f-9665-4bd2-941d-1f59df3d128f
2018-01-30T01:33:43.587Z LOG lightOff
2018-01-30T01:33:43.587Z LOG new brain state: pendingIdle
2018-01-30T01:33:43.588Z LOG New sessionId: 1c95361b-95a0-4355-a286-680bc87be61f
2018-01-30T01:33:43.588Z LOG lightOff
2018-01-30T01:33:43.589Z LOG lamassu-machine bailing out momentarily...
2018-01-30T01:33:43.590Z LOG [TypeError: Object [object Object] has no method 'raqia']
2018-01-30T01:33:43.591Z LOG TypeError: Object [object Object] has no method 'raqia'
    at /Users/darshil/Documents/Programming/Orgs/bitcoin-atm/lib/brain.js:792:17
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
2018-01-30T01:33:43.597Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:43.702Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:43.803Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:43.904Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.005Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.111Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.215Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.320Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.421Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.522Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.628Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.729Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.835Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:44.939Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.044Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.144Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.247Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.349Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.454Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.554Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.654Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.757Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.862Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:45.964Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:46.065Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:46.170Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:46.272Z LOG DEBUG101: initialize, 0x1b, null
2018-01-30T01:33:46.375Z LOG FSM: disable [ Initialize -> Disable ]
2018-01-30T01:33:46.376Z LOG DEBUG100: getEnabled
2018-01-30T01:33:50.593Z LOG lamassu-machine bailing out
2018-01-30T01:33:50.594Z LOG lamassu-machine exiting`

**Comment by darshil** [comment]
2018-01-30T02:25:06.792Z LOG [TypeError: Object [object Object] has no method 'raqia']
2018-01-30T02:25:06.792Z LOG TypeError: Object [object Object] has no method 'raqia'
    at /Users/darshil/Documents/Programming/Orgs/bitcoin-atm/lib/brain.js:792:17
    at fs.js:207:20

**Comment by darshil** [comment]
cc: @naconner

**Comment by naconner** [comment]
Hi. The logs show you're using lamassu-machine v2 instead of v3. 

Our instructions for running the machine locally can be found here: https://github.com/lamassu/lamassu-machine/wiki/Running-v3-locally-on-Debian-or-Ubuntu
